version: "3.8"

services:
  backend:
    build: ./backend
    container_name: student-loan-backend
    ports:
      - "3333:3333"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: sh -c "npx prisma migrate deploy && npm run dev"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: student-loan-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src # monta só o código fonte, não o node_modules
      - ./frontend/public:/app/public
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/package.json:/app/package.json
      - ./frontend/tsconfig.json:/app/tsconfig.json
    environment:
      # Use o nome do serviço backend, não "localhost"
      - VITE_API_URL=http://backend:3333
    command: npm run dev

  db:
    image: postgres
    container_name: student-loan-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: financiamento_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
