services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: financiamento_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
